### ISSUE TITLE
Add a screenshot of the config page

### ISSUE THREAD

**Issue by vimaljoseph** [zyxware/asset-expiry-tracker#1]
![Config](https://github.com/zyxware/asset-expiry-tracker/assets/109938/c06fa7da-317c-4f5d-82e0-8869511b79c5)

**Comment by ArjunGR7** [comment]
![Asset Tracker Config screenshot](https://github.com/zyxware/asset-expiry-tracker/assets/137140972/447bcb5e-f98d-4677-8a96-154fc1a2412c)
